### ISSUE TITLE
Can't Display the login form again.

### ISSUE THREAD

**Issue by E1991M02S01** [spring-guides/tut-spring-boot-oauth2#22]
Hello, I am trying to display the login form again once I have clicked the 'logout button', but it seems that the information of the user is already persisted in somewhere. How Can I display the Login Form again, everytime I hit the logout button?

**Comment by dsyer** [comment]
The login form in this project is no hosted in the app (it is in the provider). So it doesn't really make sense to jump out of the app on successful logout and over to the provider (apart from anything else the browser is probably already authenticated there, so you don't even see a form as such), which is why the success handler is set to redirect to "/" (the home page).
