### ISSUE TITLE
Converting to JWT in the social login authorization server example

### ISSUE THREAD

**Issue by ffazil** [spring-guides/tut-spring-boot-oauth2#42]
Am trying to convert the token issued in the social login authorization server example by `JwtAccessTokenConverter` like below 
    
    @Bean
    public TokenStore tokenStore() {
        return new JwtTokenStore(accessTokenConverter());
    }

    @Bean
    public JwtAccessTokenConverter accessTokenConverter() {
        JwtAccessTokenConverter converter = new JwtAccessTokenConverter();
        converter.setSigningKey("123");
        return converter;
    }

    @Bean
    @Primary
    public DefaultTokenServices tokenServices() {
        final DefaultTokenServices tokenServices = new DefaultTokenServices();
        tokenServices.setTokenStore(tokenStore());
        return tokenServices;
    }
and configuring the endpoints like

    final TokenEnhancerChain tokenEnhancerChain = new TokenEnhancerChain();
        tokenEnhancerChain.setTokenEnhancers(
                Arrays.asList(accessTokenConverter()));

        endpoints.tokenStore(tokenStore())
                .tokenEnhancer(tokenEnhancerChain)
                .authenticationManager(authenticationManager);
But the `/oauth/token` endpoint still does not issue a JWT. Am I missing something here.

**Comment by dsyer** [comment]
Looks kind of alright to me. Maybe a sample app would make it easier to see?

**Comment by startext** [comment]
Hello guys!
Do you have any progress here?
Very interesting to see your results.
Thanks in advance

**Comment by alienintheheights** [comment]
Same issue here. I want to generate a JWT instead of the UUID token but as soon as I introduce a AuthorizationServerConfigurerAdapter class to this sample, even without any configure overrides, the tokens are no longer generated. The error in the log is AccessDenied, which I presume is because the default AuthenticationManager is not suited for this? I feel like I'm missing something obvious here. My goal is to use this AuthorizationServer as a proxy for an external OAuth2 server and deliver tokens to its clients that contain information captured during the external OAuth2 login. Maybe that's not possible?

2019-02-10 12:20:54.397 DEBUG 10639 --- [nio-9025-exec-1] o.s.s.w.a.ExceptionTranslationFilter     : Access is denied (user is anonymous); redirecting to authentication entry point

org.springframework.security.access.AccessDeniedException: Access is denied
